/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import Classes.Book;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Frame;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author pedro
 */
public class BookDetailScreen extends JFrame {

    private final Book book;

    /**
     * Creates new form BookDetailScream
     */
    public BookDetailScreen(Frame par, boolean par1, Book book){

        initComponents();
        this.book = book;
        setTitle("Titulo: " + book.getTitulo());
        StringBuilder autoresStr = new StringBuilder();
        List<String> autores = book.getAutores();

        for (String autor : autores) {
            autoresStr.append(autor).append(", ");
        }
        autoresStr.setLength(autoresStr.length() - 2);
        labelAutor.setText(autoresStr.toString());
        labelEditora.setText(book.getEditora());
        labelPreco.setText(String.format("%.2f", book.getPreco()));
        URL url;
        try {
            url = new URL(book.getImagem());
            ImageIcon imageIcon = new ImageIcon(url);
            jLabel6.setIcon(imageIcon);
        } catch (MalformedURLException ex) {
            Logger.getLogger(BookDetailScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(book.isDisponivelPdf() == true){
            labelPdf.setText("Possui PDF");
        }
        else{
            labelPdf.setText("Nao Possui PDF");
        }
        

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelAutor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelEditora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelPreco = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelPdf = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Autor(es):");

        labelAutor.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        labelAutor.setText("jLabel3");

        jLabel4.setText("Editora:");

        labelEditora.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        labelEditora.setText("jLabel5");

        jLabel5.setText("Preço:");

        labelPreco.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        labelPreco.setText("jLabel6");

        jLabel1.setText("PDF:");

        labelPdf.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        labelPdf.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAutor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEditora))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPreco))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPdf)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelAutor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelEditora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(labelPreco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labelPdf))
                        .addGap(0, 121, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookDetailScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookDetailScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookDetailScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookDetailScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> {
            ArrayList<String> authors = new ArrayList<>();
            authors.add("Author 1");
            authors.add("Author 2");

            Book book = new Book("Example Title", authors, "Example Publisher", true, 100.0, "https://drive.usercontent.google.com/download?id=15tzOCQdSRGg_wcwa-3TnpS2zt2hTHaMI&authuser=0&confirm=t&uuid=e7d297b8-bf30-49d6-bd25-c0cbdbc140bf&at=APZUnTWC7Q_RZ5u--BGCMZLVqgup:1718315906981");
            BookDetailScreen dialog = new BookDetailScreen(null, true, book);
            dialog.setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelEditora;
    private javax.swing.JLabel labelPdf;
    private javax.swing.JLabel labelPreco;
    // End of variables declaration//GEN-END:variables
}
